#!/bin/sh
cd "$(dirname "$0")"
export LD_LIBRARY_PATH="/system/lib64:$LD_LIBRARY_PATH"
export QT_PLUGIN_PATH="../../phonelibs/qt-plugins/$(uname -m)"
if [ -f /TICI ]; then
  exec ./_ui_c3
else
  exec ./_ui
fi
